# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f9895581-1bb9-4451-b32a-26d31dbbf8a2";
    fsType = "btrfs";
    options = ["subvol=@nixos"];
  };

  boot.initrd.luks.devices."cryptlvm".device = "/dev/disk/by-uuid/218b0149-7cef-46ec-b939-88b72a2c3003";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f9895581-1bb9-4451-b32a-26d31dbbf8a2";
    fsType = "btrfs";
    options = ["subvol=@nixos-home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f9895581-1bb9-4451-b32a-26d31dbbf8a2";
    fsType = "btrfs";
    options = ["subvol=@nixos-nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/04A5-A822";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
